#!/bin/bash

if [[ $XDG_SESSION_TYPE == x11 ]]; then
    MOZ_X11_EGL=1 firejail /usr/bin/firefox "$@"
elif [[ $XDG_SESSION_TYPE == wayland ]]; then
    GDK_BACKEND=wayland MOZ_ENABLE_WAYLAND=1 firejail /usr/bin/firefox "$@"
else
    firejail /usr/bin/firefox "$@"
fi
exit "$?"
