#!/bin/bash

res=$(xrandr | grep -m1 -Po "connected.+\d+x\d+" | cut -d\  -f2)
width=$(echo "$res" | cut -dx -f1)
height=$(($(echo "$res" | cut -dx -f2)-44))
res="${width}x${height}"
unset width height

cmd=(
    firejail
        --whitelist=~/.config/mpv --noblacklist=~/.config/mpv
        --whitelist=/run/media --noblacklist=/run/media
        --whitelist=~/Documents/x --noblacklist=~/Documents/x
        --whitelist=~/Transfers --noblacklist=~/Transfers
      	--whitelist=~/TV --noblacklist=~/TV
        --ignore=dbus
        /usr/bin/mpv --autofit=$res "$@"
)
echo "${cmd[@]}" | xargs
"${cmd[@]}"
