#!/bin/bash

# Use https://github.com/mpv-player/mpv-build for sofalizer.
mpv=~/bin/.mpv
cmd=(
    firejail
        --whitelist=~/.config/mpv --noblacklist=~/.config/mpv
        --whitelist=/run/media --noblacklist=/run/media
        --whitelist=~/Transfers --noblacklist=~/Transfers
        --whitelist=~/TV --noblacklist=~/TV
        --whitelist="$mpv" --noblacklist="$mpv"
        --ignore=dbus
        "$mpv" "$@"
)
echo "${cmd[@]}" | xargs
"${cmd[@]}"
