#!/bin/bash

[[ ! -f ~/bin/.steam ]] && echo -ne '#!/bin/bash\ncd ~/Documents/SteamIdleMaster\nsteam "$@" &> /dev/null &\nbash\n' > ~/bin/.steam && chmod u+x ~/bin/.steam

firejail \
-ignore=seccomp \
--noblacklist=~/.config/vkBasalt \
--whitelist=~/.config/vkBasalt \
--noblacklist=~/.reshade \
--whitelist=~/.reshade \
--whitelist=~/.cache/mesa_shader_cache \
--noblacklist=~/.cache/mesa_shader_cache \
--noblacklist=~/.config/MangoHud/MangoHud.conf \
--whitelist=~/.config/MangoHud/MangoHud.conf \
--noblacklist=~/Documents/SteamIdleMaster \
--whitelist=~/Documents/SteamIdleMaster \
--noblacklist=~/bin/.steam \
--whitelist=~/bin/.steam \
--profile=steam bash \
-c ~/bin/.steam "$@"
